// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string  `json:"id"`
	Content  string  `json:"content"`
	User     *User   `json:"user"`
	ParentID *string `json:"parentId,omitempty"`
	PostID   string  `json:"postId"`
}

type CommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Content  string  `json:"content"`
}

type Mutation struct {
}

type Post struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Content     string     `json:"content"`
	User        *User      `json:"user"`
	Commentable bool       `json:"commentable"`
	Comments    []*Comment `json:"comments"`
}

type PostInput struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Commentable bool   `json:"commentable"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
